<?php

namespace App\DPPA;

use App\Scopes\TahunAnggaranScope;
use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
    protected $table = 'dppa_program';

    protected $fillable = ['kode','nama','tahun_anggaran'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new TahunAnggaranScope());
    }

    public function kegiatan(){
        return $this->hasMany(Kegiatan::class,'program_id');
    }

    public function sub_kegiatan()
    {
        return $this->hasManyThrough(Kegiatan::class, Sub_Kegiatan::class,'program_id','kegiatan_id');
    }

}
