<?php

namespace App\Dppa;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Sub_Kegiatan extends Model
{
    protected $table = 'dppa_sub_kegiatan';
    
    protected $fillable = ['nama','jumlah_anggaran','kegiatan_id','kode_rekening','uraian'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('tahun_anggaran_scope',function (Builder $builder){
            $builder->whereHas('kegiatan.program',function($query){
                $query->where('tahun_anggaran','=',2016);
            });
        });
    }

    public function kegiatan()
    {
        return $this->belongsTo(Kegiatan::class,'kegiatan_id');
    }

    public function uraian()
    {
        return $this->belongsTo(Uraian_Sub_Kegiatan::class, 'uraian_id');
    }
}
