<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    protected $table = 'pembayaran';

    protected $fillable = [
        'perjalanan_dinas_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('tahun_anggaran_scope',function (Builder $builder){
            $builder->whereHas('perjalanan_dinas');
        });
    }

    public function perjalanan_dinas()
    {
        return $this->belongsTo(PerjalananDinas::class,'perjalanan_dinas_id');
    }

    public function petugas_pembayaran()
    {
        return $this->hasMany(PetugasPembayaran::class,'pembayaran_id');
    }
}
