<?php

namespace App;

use App\Console\Kernel;
use App\Dppa\Kegiatan;
use App\Dppa\Sub_Kegiatan;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class PerjalananDinas extends Model
{
    protected $table = 'perjalanan_dinas';

    protected $fillable = [
        'tahun_anggaran',
        'kegiatan_id',
        'sub_kegiatan_id',
        'tempat_berangkat',
        'tempat_tujuan',
        'tanggal_berangkat',
        'tanggal_pulang',
        'referensi_perjalanan',
        'nomor_referensi',
        'tanggal_referensi',
        'jenis_perjalanan',
        'tingkat_biaya_perjalanan_dinas',
        'maksud_perjalanan',
        'alat_angkutan_yang_digunakan',
        'keterangan_lain_lain',
        'pejabat_pelaksana_teknis_kegiatan',
        'pejabat_pengadaan_barang_dan_jasa',
        'pejabat_kuasa_pengguna_anggaran'
    ];

    protected $attributes = [
        'tahun_anggaran' => 2016
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('tahun_anggaran_scope',function (Builder $builder){
            $builder->whereHas('kegiatan');
        });
    }

    public function kegiatan()
    {
        return $this->belongsTo(Kegiatan::class,'kegiatan_id');
    }

    public function sub_kegiatan()
    {
        return $this->belongsTo(Sub_Kegiatan::class, 'sub_kegiatan_id');
    }
}
