<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class TransaksiPerjalananDinas extends Model
{
    protected $table = 'transaksi_perjalanan_dinas';

    protected $fillable = [
        'perjalanan_dinas_id',
        'nomor_surat',
        'ketua_perjalanan_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('tahun_anggaran_scope',function (Builder $builder){
            $builder->whereHas('perjalanan_dinas');
        });
    }

    public function perjalanan_dinas()
    {
        return $this->belongsTo(PerjalananDinas::class,'perjalanan_dinas_id');
    }

    public function ketua_perjalanan()
    {
        return $this->belongsTo(Pegawai::class,'ketua_perjalanan_id');
    }

    public function petugas()
    {
        return $this->hasMany(PetugasTransaksiPerjalananDinas::class, 'transaksi_perjalanan_dinas_id');
    }

    public function pejabat()
    {
        return $this->hasMany(PejabatTransaksiPerjalananDinas::class, 'transaksi_perjalanan_dinas_id');
    }
}
